const product = [
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
    {
        name:"",
        items:[
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            },
            {
                title:"",
                content:"",
                image:""
            }
        ]
    },
]
